AY2425S1-CS2103-F12-4/tp

docs/AboutUs.md

Update Qing Khang's details

---

docs/AboutUs.md

Update Wei Loon's Details

---

docs/DeveloperGuide.md

Update the DG: Non-Functional Requirements

---

docs/AboutUs.md
docs/DeveloperGuide.md
docs/UserGuide.md
docs/_markbind/layouts/default.md
docs/index.md

Update site-wide settings

---

docs/DeveloperGuide.md

Update DG: Add Glossary

---

docs/DeveloperGuide.md

Update DG : Add Use Cases

---

docs/DeveloperGuide.md

Update DG: Use case numbering UC11

---

src/main/java/seedu/address/logic/commands/AddEmergencyContactNameCommand.java
src/main/java/seedu/address/logic/parser/AddEmergencyContactNameCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/test/java/seedu/address/logic/commands/AddEmergencyContactNameCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddEmergencyContactNameCommandParserTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Add Emergency Contact Name Command and Parser

---

docs/UserGuide.md

Edit UG to include Add Student's Class functionality

---

docs/UserGuide.md

Edit UG to include Add Student's Sex functionality

---

docs/UserGuide.md

Edit UG to include Add Student's Register Number functionality

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/EmergencyPhoneCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EmergencyPhoneCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/EmergencyPhone.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EmergencyPhoneCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/EmergencyPhoneCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/EmergencyPhoneTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Finish Add Emergency Contact Number Command

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddEmergencyContactNameCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/EmergencyPhoneCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddEmergencyContactNameCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/EmergencyContactName.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/AddEmergencyContactNameCommandTest.java
src/test/java/seedu/address/logic/parser/AddEmergencyContactNameCommandParserTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/EmergencyContactNameTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Complete Emergency Contact Name functionality

---

docs/UserGuide.md
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddEcNumberCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddEcNumberCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/EcNumber.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java

Add edit ECNUMBER functionality

---

docs/UserGuide.md

Update UserGuide with changes

---

src/main/java/seedu/address/logic/parser/AddAttendanceCommandParser.java
src/main/java/seedu/address/model/person/AbsentReason.java
src/test/java/seedu/address/logic/parser/AddAttendanceParserTest.java
src/test/java/seedu/address/model/person/AbsentReasonTest.java

Fix bug when deleting attendance

---

docs/DeveloperGuide.md

Update addAttendance Use Case in DG

---

src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteExamCommandParser.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteExamCommandTest.java
src/test/java/seedu/address/logic/parser/AddExamCommandParserTest.java
src/test/java/seedu/address/logic/parser/AddExamScoreCommandParserTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/DeleteExamCommandParserTest.java

Add functionality to delete Exam

---

docs/DeveloperGuide.md

Update DG: addExam/addExamScore

---

src/main/java/seedu/address/model/person/AbsentDate.java
src/test/java/seedu/address/logic/commands/AddAttendanceTest.java
src/test/java/seedu/address/model/person/AbsentDateTest.java

Fix bug where invalid dates are allowed

---

src/main/java/seedu/address/logic/commands/AddAttendanceCommand.java
src/test/java/seedu/address/logic/commands/AddAttendanceTest.java

Fix AddAttendance UI message for deleting unrecorded attendance

---

src/main/java/seedu/address/logic/commands/AddAttendanceCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java

Fix absent date prefix

---

src/main/java/seedu/address/logic/parser/AddAttendanceCommandParser.java

Fix bug where multiple dates and reasons are allowed in input

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddSubmissionCommand.java
src/main/java/seedu/address/logic/parser/AddSubmissionCommandParser.java
src/main/java/seedu/address/logic/parser/AddSubmissionStatusCommandParser.java
src/main/java/seedu/address/model/submission/Submission.java

closes #114, closes #116, closes #117, closes #101

Branch fix alpha bugs

---

docs/DeveloperGuide.md

Update DG for Sorting

---

src/main/java/seedu/address/logic/parser/ParserUtil.java

Remove unnecessary spaces in absent reason

---

src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/model/person/PersonPredicate.java
src/test/java/seedu/address/logic/commands/FilterCommandTest.java
src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
src/test/java/seedu/address/model/person/PersonPredicateTest.java

Fixes #109 
Testing has been added to test out filter functionality, and code quality has been improved to follow more OOP principles.

Branch - improve filter code quality

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddExamCommand.java
src/main/java/seedu/address/logic/commands/AddExamScoreCommand.java
src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
src/main/java/seedu/address/logic/parser/AddExamCommandParser.java
src/main/java/seedu/address/logic/parser/AddExamScoreCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteExamCommandParser.java
src/main/java/seedu/address/model/exam/Exam.java
src/test/java/seedu/address/logic/commands/AddExamScoreCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/model/exam/ExamTest.java

Closes #162
Closes #163
Closes #143
Closes #142
Closes #138
Closes #126

Bugfixes for AddExam/AddExamScore/DeleteExam

---

docs/DeveloperGuide.md
docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml

Closes #187 
Closes #175 
Closes #173 
Closes #172

Update DG: addAttendance

---

src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
src/test/java/seedu/address/model/person/AbsentDateTest.java
src/test/java/seedu/address/model/person/AbsentReasonTest.java

Improve code quality on test cases

---

docs/DeveloperGuide.md
docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml

Add submission into uml diagrams

---

src/main/java/seedu/address/model/person/StudentClass.java
src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
src/test/java/seedu/address/model/person/StudentClassTest.java
src/test/java/seedu/address/model/submission/SubmissionTest.java

Improve test code by splitting by equivalence partitions

---

docs/DeveloperGuide.md

Update DG for instructions for manual testing

---

docs/DeveloperGuide.md

Updated glossary for some terms related to emergency contact and sorting.
Closes #174

Update DG: Manual testing for addEcNumber, Sort, Edit

---

docs/DeveloperGuide.md
docs/diagrams/BetterModelClassDiagram.puml
docs/diagrams/ModelClassDiagram.puml

Closes #186 
Closes #179 
Closes #176

Exam: Update DG and UML Diagrams

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddEcNumberCommand.java
src/main/java/seedu/address/logic/commands/SortCommand.java
src/main/java/seedu/address/logic/parser/AddEcNumberCommandParser.java
src/main/java/seedu/address/logic/parser/SortCommandParser.java

Adjust some formatting for UG and DG
Add more defensive coding

Polish up code

---

src/main/java/seedu/address/logic/commands/AddEcNameCommand.java
src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/logic/parser/AddEcNameCommandParser.java
src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/logic/parser/FilterCommandParserHelper.java
src/main/java/seedu/address/model/person/EcName.java
src/test/java/seedu/address/logic/commands/AddEcNameCommandTest.java
src/test/java/seedu/address/logic/commands/FilterCommandTest.java
src/test/java/seedu/address/logic/parser/AddEcNameCommandParserTest.java
src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
src/test/java/seedu/address/model/person/EcNameTest.java

Improve code quality

---

docs/DeveloperGuide.md

Remove line breaks

---

src/main/java/seedu/address/model/person/StudentClass.java

Fix grammer issue in message

---

docs/DeveloperGuide.md
docs/UserGuide.md

Update for planned enhancements and known bugs
